course_id = "43754"

[canvas]
url = "https://boisestatecanvas.instructure.com/"
token = "15177~HmTELDkkyAQTXctakDmUt9B3MKYKeWKYJVE36zumEJJZ6u8th9TKPwA3WBTMJ9F2"
drop_columns = ["_requester"]

[ally]
region = "prod.ally.ac"
client_id = "11637"
bearer_token = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7InJvbGUiOiJBbGx5Q291cnNlUmVwb3J0QXBpVXNlciIsIm5hbWUiOiI8Pjw-IiwiY2xpZW50SWQiOjExNjM3LCJ1c2VySWQiOiItMSJ9LCJleHAiOjE3OTk2NDQ5NjMsImlhdCI6MTc2ODEwODk2M30.ZhwWla72CNEvLg8v_1DwyD1XlvMVaC-xuFss9H-cgNM"
key = "HA41OiNhgkYSDAqHohaF4ZVCzeeywf0o"
secret = "QNq1PwOFUbww0omh3IgTIwJcU00gEKHg"
flag_columns = [
    'AlternativeText:2',
    'Contrast:2', 'HeadingsHigherLevel:3', 'HeadingsPresence:2',
    'HeadingsSequential:3', 'HeadingsStartAtOne:3', 'HtmlBrokenLink:2',
    'HtmlCaption:2', 'HtmlColorContrast:2', 'HtmlDefinitionList:3',
    'HtmlEmptyHeading:2', 'HtmlEmptyTableHeader:2', 'HtmlHasLang:3',
    'HtmlHeadingOrder:3', 'HtmlHeadingsPresence:2', 'HtmlHeadingsStart:2',
    'HtmlImageAlt:2', 'HtmlImageRedundantAlt:3', 'HtmlLabel:2',
    'HtmlLinkName:3', 'HtmlList:3', 'HtmlObjectAlt:2', 'HtmlTdHasHeader:2',
    'HtmlTitle:3', 'ImageContrast:2', 'ImageDecorative:2',
    'ImageDescription:2', 'ImageOcr:3', 'ImageSeizure:1',
    'LanguageCorrect:3', 'LanguagePresence:3', 'Ocred:2', 'Parsable:1',
    'Scanned:1', 'Security:1', 'TableHeaders:2', 'Tagged:2', 'Title:3'
]

[joint]
drop_columns = [
    "upload_status",
    "size",
    "created_at",
    "created_at_date",
    "updated_at",
    "updated_at_date",
    "unlock_at",
    "locked",
    "lock_at",
    "hidden_for_user",
    "modified_at",
    "modified_at_date",
    "media_entry_id",
    "locked_for_user",
    "Deleted at",
    "Url",
    "visibility_level",
    "size_date",
    "category"
]

# [content_types]
# "wordprocessingml.document" = "Word Document"
# "spreadsheetml.sheet" = "Excel Spreadsheet"
# "presentationml.presentation" = "PowerPoint Presentation"
# "application/pdf" = "PDF Document"
# "text/html" = "HTML Document"
# "application/zip" = "ZIP Archive"
# "application/x-zip-compressed" = "ZIP Archive"
# full_mime_type.startswith("image/") = "Image"
# full_mime_type.startswith("audio/") = "Audio"
# full_mime_type.startswith("video/") = "Video"
# full_mime_type.startswith("text/") = "Text Document"
# full_mime_type.startswith("application/"):
#         return full_mime_type.split('/')[-1].replace('.', ' ').replace('-', ' ').title() + " File"


[content_types]
[content_types.Pages]
method = "get_pages"
html_field = "body"
title_field = "title"
keyword_params = { include = ["body"] }

[content_types.Files]
method = "get_files"
html_field = "N/A"
title_field = "display_name"
keyword_params = {}  # TOML supports inline dictionaries!

[content_types.Assignments]
method = "get_assignments"
html_field = "description"
title_field = "name"
keyword_params = {}

[content_types.Discussions]
method = "get_discussion_topics"
html_field = "message"
title_field = "title"
keyword_params = {}

[content_types.Quizzes]
method = "get_quizzes"
html_field = "description"
title_field = "title"
keyword_params = {}