"""Retrieve and combine data for a single course from both ally and canvas."""

import sys
from typing import TYPE_CHECKING

import pandas as pd
from canvasapi import Canvas
from loguru import logger
from pandas.core.frame import DataFrame

if TYPE_CHECKING:
    from canvasapi.course import Course
    from canvasapi.file import File
    from canvasapi.paginated_list import PaginatedList
    from pandas.core.frame import DataFrame


# =============================================================================
# CONFIGURATION - General/Display
# =============================================================================

pd.options.display.float_format = lambda x: f"{x:.3f}"
pd.options.display.max_rows = 500
pd.options.display.max_columns = 100
pd.set_option("display.precision", 4)


# =============================================================================
# CONFIGURATION - Logger
# =============================================================================
logger.remove()
_stderr_logger = logger.add(
    sys.stderr,
    colorize=True,
    format="<green>{time:YYYY-MM-DD at HH:mm:ss}</green>| <level>{level}</level> | <level>{message}</level> | {extra}",
    backtrace=True,
    diagnose=True,
    level="TRACE",
)
_file_logger = logger.add(
    "accessibility_checklist_generator.log",
    colorize=True,
    rotation="1 week",
    retention=5,
    format="<green>{time:YYYY-MM-DD at HH:mm:ss}</green>| <level>{level}</level> | <level>{message}</level> | {extra}",
    backtrace=True,
    diagnose=True,
    level="TRACE",
)
# =============================================================================
# CONSTANTS - API Configuration
# =============================================================================

canvas_url = "https://boisestatecanvas.instructure.com/"
canvas_token = (
    "15177~HmTELDkkyAQTXctakDmUt9B3MKYKeWKYJVE36zumEJJZ6u8th9TKPwA3WBTMJ9F2"
)
canvas_columns = [
    "id",
    "folder_id",
    "folder_id_date",
    "display_name",
    "filename",
    "upload_status",
    "content-type",
    "url",
    "size",
    "created_at",
    "created_at_date",
    "updated_at",
    "updated_at_date",
    "unlock_at",
    "locked",
    "hidden",
    "lock_at",
    "hidden_for_user",
    "thumbnail_url",
    "modified_at",
    "modified_at_date",
    "mime_class",
    "media_entry_id",
    "category",
    "locked_for_user",
    "visibility_level",
    "size_date",
]
drop_canvas_columns = ["_requester"]
drop_joint_columns = [
    "upload_status",
    "size",
    "created_at",
    "created_at_date",
    "updated_at",
    "updated_at_date",
    "unlock_at",
    "locked",
    "lock_at",
    "hidden_for_user",
    "modified_at",
    "modified_at_date",
    "media_entry_id",
    "locked_for_user",
    "Deleted at",
    "Url",
    "visibility_level",
    "size_date",
    "category",
]

ally_region = "prod.ally.ac"
ally_client_id = "11637"
ally_bearer_token = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7InJvbGUiOiJBbGx5Q291cnNlUmVwb3J0QXBpVXNlciIsIm5hbWUiOiI8Pjw-IiwiY2xpZW50SWQiOjExNjM3LCJ1c2VySWQiOiItMSJ9LCJleHAiOjE3OTk2NDQ5NjMsImlhdCI6MTc2ODEwODk2M30.ZhwWla72CNEvLg8v_1DwyD1XlvMVaC-xuFss9H-cgNM"
ally_key = "HA41OiNhgkYSDAqHohaF4ZVCzeeywf0o"
ally_secret = "QNq1PwOFUbww0omh3IgTIwJcU00gEKHg"
course_id = 31318


# =============================================================================
# FUNCTIONS
# =============================================================================
@logger.catch(
    message="Failed to fetch Canvas course content. See traceback for details.",
)
def fetch_canvas_course(
    canvas_url: str,
    canvas_token: str,
    course_id: int,
    drop_cols: list[str] = ["_requester"],
    dtypebackend: str = "pyarrow",
) -> DataFrame:
    """Download canvas course info and load it into a Pandas DataFrame.

    Parameters
    ----------
    canvas_url: str
        The base url for your institution's canvas site.
    canvas_token: str
        Access token generated by the user from within the canvas user settings.
    course_id : int
        ID number associated with the course site you are auditing.
    drop_cols: list[str], optional
        List of columns you don't need (["_requester"], by default)
    dtypebackend: str, optional
        The dtype backend you want for your dataframe ("pyarrow", by default)

    Returns
    -------
    canvas_df: DataFrame
        A pandas DataFrame

    """
    logger.info("Initializing Canvas object...")
    canvas: Canvas = Canvas(canvas_url, canvas_token)
    logger.info("Fetching course site data...")
    course: Course = canvas.get_course(course_id)
    logger.info("Fetching course files data...")
    course_files: PaginatedList[File] = course.get_files()

    logger.info("Initializing DataFrame")
    canvas_df: DataFrame = (
        pd.DataFrame([file.__dict__ for file in course_files])
        .drop(columns=drop_cols)
        .convert_dtypes(dtype_backend=dtypebackend)
    )
    return canvas_df


@logger.catch(
    message="Failed to load ally DataFrame. See traceback for details.",
)
def create_ally_df(
    file_path: str,
    dtypebackend: str = "pyarrow",
    use_columns: list[str] | None = None,
    show_deleted: bool = False,
) -> DataFrame:
    """Create a Pandas DataFrame from a downloaded Ally course report.

    Parameters
    ----------
    file_path: Path | str
        The full or relative path of the downloaded course report.
    use_columns: list[str], optional
        Set of columns to include, by default includes all columns.
    dtypebackend: str
        The dtype backend you want for your dataframe ("pyarrow", by default)

    Returns
    -------
    ally_df: DataFrame
        A pandas DataFrame

    """
    try:
        ally_df = pd.read_csv(
            file_path,
            dtype_backend=dtypebackend,
            usecols=use_columns,
            engine="pyarrow",
        ).rename(columns={"Name": "display_name"})
    except Exception as e:
        logger.critical("Pandas load failed: %s", e)
        raise
    # ally_df[["Item type","id"]]=ally_df["Id"].str.split(":",expand=True)
    # ally_df=ally_df.set_index("id")
    if show_deleted == True:
        return ally_df
    return ally_df.loc[ally_df["Deleted at"].isna()]


@logger.catch(message="Failed to join DataFrames. See traceback for details.")
def join_data_sources(
    canvas_df: DataFrame,
    ally_df: DataFrame,
    drop_cols: list[str] | None = None,
) -> DataFrame:
    """Join Ally and Canvas DataFrames on their corresponding file name columns.

    Parameters
    ----------
    canvas_df: DataFrame
        DataFrame of all files from Canvas course site. (Could also be all content from canvas if you create it right.)
    ally_df: DataFrame
        DataFrame of all content in Canvas course site that Ally has checked for accessibility.

    Returns
    -------
    joint_df: DataFrame
        A pandas DataFrame that combines the data from Canvas and Ally.

    """
    joint_df = pd.merge(
        canvas_df.copy(),
        ally_df.copy(),
        on="display_name",
        how="outer",
    )
    return joint_df.dropna(subset="Score").drop(
        drop_cols,
        axis="columns",
    )


@logger.catch(
    message="Failed to write {df} to CSV. See trackeback for details.",
)
def create_csv(df: DataFrame) -> None:
    df["Score"] = df["Score"] * 100
    return df.to_csv(
        "accessibility_review.csv",
        na_rep="",
        mode="x",
        float_format="%.2f",
    )


# =============================================================================
# EXECUTION - Orchestrator
# =============================================================================
if __name__ == "__main__":
    canvas_df = fetch_canvas_course(canvas_url, canvas_token, course_id)
    ally_df = create_ally_df(
        "/Users/harkmorper/Downloads/ally-31318-OPPrimary_-_SOCWRK_526_-_The_Evaluation_and_Treatment_of_Mental_Disorders_-2026-01-12-15-11.csv",
    )
    joint_df = join_data_sources(canvas_df, ally_df, drop_joint_columns)
    create_csv(joint_df)
    success_message = "Congratulations! DataFrame written to CSV!"
    logger.success(success_message)
    print(success_message)
