"""Retrieve and combine data for a single course from both ally and canvas."""

import sys
import tomllib
from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd
from canvasapi import Canvas
from loguru import logger
from pandas.core.frame import DataFrame

if TYPE_CHECKING:
    from canvasapi.course import Course
    from canvasapi.file import File
    from canvasapi.paginated_list import PaginatedList
    from pandas.core.frame import DataFrame


# =============================================================================
# CONFIGURATION - General/Display
# =============================================================================

pd.options.display.float_format = lambda x: f"{x:.3f}"
pd.options.display.max_rows = 500
pd.options.display.max_columns = 100
pd.set_option("display.precision", 4)


# =============================================================================
# CONFIGURATION - Logger
# =============================================================================
logger.remove()
_stderr_logger = logger.add(
    sys.stderr,
    colorize=True,
    format="<green>{time:YYYY-MM-DD at HH:mm:ss}</green>| <level>{level}</level> | <level>{message}</level> | {extra}",
    backtrace=True,
    diagnose=True,
    level="TRACE",
)
_file_logger = logger.add(
    "accessibility_checklist_generator.log",
    colorize=True,
    rotation="1 week",
    retention=5,
    format="<green>{time:YYYY-MM-DD at HH:mm:ss}</green>| <level>{level}</level> | <level>{message}</level> | {extra}",
    backtrace=True,
    diagnose=True,
    level="TRACE",
)
# =============================================================================
# SET-UP
# =============================================================================
PROJECT_ROOT = Path(__file__).parent.parent
config_file = PROJECT_ROOT / "config.toml"


# =============================================================================
# FUNCTIONS
# =============================================================================
@logger.catch()
def load_config(config_path=config_file) -> dict:
    """Parse toml file containing configuration and data schema rules.

    Return:
    Dictionary containing all rules, equivalencies, and configuration settings.

    """
    try:
        with Path(config_path).open("rb") as f:
            return tomllib.load(f)
    except FileNotFoundError:
        logger.exception(f"Config file {config_path} not found.")
        return {}


@logger.catch(
    message="Failed to fetch Canvas course content. See traceback for details.",
)
def fetch_canvas_course(
    config_dict,
    dtypebackend: str = "pyarrow",
) -> DataFrame:
    """Download canvas course info and load it into a Pandas DataFrame.

    Parameters
    ----------
    canvas_url: str
        The base url for your institution's canvas site.
    canvas_token: str
        Access token generated by the user from within the canvas user settings.
    course_id : int
        ID number associated with the course site you are auditing.
    drop_cols: list[str], optional
        List of columns you don't need (["_requester"], by default)
    dtypebackend: str, optional
        The dtype backend you want for your dataframe ("pyarrow", by default)

    Returns
    -------
    canvas_df: DataFrame
        A pandas DataFrame

    """
    canvas_url = config_dict.get("canvas").get("url")
    canvas_token = config_dict.get("canvas").get("token")
    drop_cols = config_dict.get("canvas").get("drop_columns")

    logger.info("Initializing Canvas object...")
    canvas: Canvas = Canvas(canvas_url, canvas_token)

    logger.info("Fetching course site data...")
    course_id = config_dict.get("course_id")
    course: Course = canvas.get_course(course_id)

    logger.info("Fetching course files data...")
    course_files: PaginatedList[File] = course.get_files()

    logger.info("Initializing DataFrame")
    canvas_df: DataFrame = (
        pd.DataFrame([file.__dict__ for file in course_files])
        .drop(columns=drop_cols)
        .convert_dtypes(dtype_backend=dtypebackend)
    )
    return canvas_df


@logger.catch(
    message="Failed to load ally DataFrame. See traceback for details.",
)
def create_ally_df(
    file_path: str,
    dtypebackend: str = "pyarrow",
    use_columns: list[str] | None = None,
    show_deleted: bool = False,
) -> DataFrame:
    """Create a Pandas DataFrame from a downloaded Ally course report.

    Parameters
    ----------
    file_path: Path | str
        The full or relative path of the downloaded course report.
    use_columns: list[str], optional
        Set of columns to include, by default includes all columns.
    dtypebackend: str
        The dtype backend you want for your dataframe ("pyarrow", by default)

    Returns
    -------
    ally_df: DataFrame
        A pandas DataFrame

    """
    try:
        ally_df = pd.read_csv(
            file_path,
            dtype_backend=dtypebackend,
            usecols=use_columns,
            engine="pyarrow",
        ).rename(columns={"Name": "display_name"})
    except Exception as e:
        logger.critical("Pandas load failed: %s", e)
        raise
    # ally_df[["Item type","id"]]=ally_df["Id"].str.split(":",expand=True)
    # ally_df=ally_df.set_index("id")
    if show_deleted == True:
        return ally_df
    return ally_df.loc[ally_df["Deleted at"].isna()]


@logger.catch(message="Failed to join DataFrames. See traceback for details.")
def join_data_sources(
    canvas_df: DataFrame,
    ally_df: DataFrame,
    drop_cols: list[str] | None = None,
) -> DataFrame:
    """Join Ally and Canvas DataFrames on their corresponding file name columns.

    Parameters
    ----------
    canvas_df: DataFrame
        DataFrame of all files from Canvas course site. (Could also be all content from canvas if you create it right.)
    ally_df: DataFrame
        DataFrame of all content in Canvas course site that Ally has checked for accessibility.

    Returns
    -------
    joint_df: DataFrame
        A pandas DataFrame that combines the data from Canvas and Ally.

    """
    joint_df = pd.merge(
        canvas_df.copy(),
        ally_df.copy(),
        on="display_name",
        how="outer",
    )
    return joint_df.dropna(subset="Score").drop(
        drop_cols,
        axis="columns",
    )


@logger.catch(
    message="Failed to write {df} to CSV. See trackeback for details.",
)
def create_csv(df: DataFrame) -> None:
    df["Score"] = df["Score"] * 100
    return df.to_csv(
        "accessibility_review.csv",
        na_rep="",
        mode="x",
        float_format="%.2f",
    )


@logger.catch()
def main(config_path: Path = config_file) -> str:
    """Orchestrate the retrieval and combining of Ally and Canvas data."""
    config = load_config(config_path)
    canvas_df = fetch_canvas_course(config)
    ally_df = create_ally_df(
        "/Users/harkmorper/Downloads/ally-31318-OPPrimary_-_SOCWRK_526_-_The_Evaluation_and_Treatment_of_Mental_Disorders_-2026-01-12-15-11.csv",
    )
    drop_joint_columns = config.get("joint").get("drop_columns")
    joint_df = join_data_sources(canvas_df, ally_df, drop_joint_columns)
    create_csv(joint_df)
    success_message = "Congratulations! DataFrame written to CSV!"
    logger.success(success_message)
    return success_message


# =============================================================================
# EXECUTION - Orchestrator
# =============================================================================
if __name__ == "__main__":
    success_message = main()
    print(success_message)
